CortexLab/CortexLab/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.mongo_admin import mongo_admin_site
from dashboard.mongo_admin import test_view
import logging

logger = logging.getLogger(__name__)
logger.info("MongoAdminSite chargé avec succès")    

urlpatterns = [
    path('mongo-test/', test_view), 
    path('mongo-admin/', mongo_admin_site.urls),  # Interface MongoDB Admin
    path('admin/', admin.site.urls),  # Interface admin standard
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('data_cleaning/', include('data_cleaning.urls', namespace='data_cleaning')),

]

CortexLab/accounts/urls.py
from django.urls import path
from .views import inscription_view, ConnexionView, DeconnexionView


app_name = 'accounts'

urlpatterns = [
    path('inscription/', inscription_view, name='inscription'),
    path('connexion/', ConnexionView, name='connexion'),
    path('deconnexion/', DeconnexionView.as_view(), name='deconnexion'),
]

CortexLab/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('projets/', views.projets_view, name='projets'),
    path('projets/create/', views.create_project, name='create_project'),
    path('projets/<str:id>/', views.view_project, name='view_project'),
    path('projets/<str:id>/analyze_data/', views.analyze_data, name='analyze_data'),
    path('projets/<str:id>/set_target/', views.set_target, name='set_target'),
    path('projets/<str:id>/set_features/', views.set_features, name='set_features'),
    path('projets/<str:id>/set_model_type/', views.set_model_type, name='set_model_type'),
    path('projets/<str:id>/delete_dataset/', views.delete_dataset, name='delete_dataset'),
    path('projets/<str:id>/prepare_analyze/', views.prepare_analyze, name='prepare_analyze'),
    path('projets/<str:id>/update_selected_datasets/', views.update_selected_datasets, name='update_selected_datasets'),

]

CortexLab/main/urls.py
from django.urls import path

from .views import base_view, dashboard_home

app_name = 'main'

urlpatterns = [
    path('', base_view, name='base'),
    path('dashboard/', dashboard_home, name='dashboard_home'),  # URL de tableau de bord
]

CortexLab/main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


def base_view(request):
    return render(request, 'main/base.html')

@login_required
def dashboard_home(request):
    return render(request, 'main/dashboard_home.html')  # Assurez-vous que le template est spécifié ici

CortexLab/main/templates/main/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mon Application{% endblock %}</title>
    <!-- Inclure vos fichiers CSS ici -->
</head>
<body>
    <header>
        <!-- En-tête de votre site avec connexion et inscription -->
        <p><a href="{% url 'accounts:connexion' %}">Connexion</a> | <a href="{% url 'accounts:inscription' %}">Inscription</a></p>
    </header>
    <main>
        {% block content %}
        <!-- Le contenu spécifique à chaque page sera inséré ici -->
        {% endblock %}
    </main>
    <footer>
        <!-- Pied de page -->
    </footer>
    <!-- Inclure vos fichiers JavaScript ici -->
</body>
</html>

CortexLab/main/templates/main/dashboard_home.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Tableau de Bord</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    </head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="navbar-left">
            <h2><a href="{% url 'main:dashboard_home' %}">Tableau de Bord</a></h2>
        </div>
        <div class="navbar-right">
            <ul>
                <li><a href="{% url 'dashboard:projets' %}">Mes Projets</a></li>
                <li><a href="{% url 'accounts:deconnexion' %}" class="logout-button">Déconnexion</a></li>
            </ul>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="main-container">
        {% block content %}
        {% endblock %}
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</html>