CortexLab/CortexLab/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.mongo_admin import mongo_admin_site
from dashboard.mongo_admin import test_view
import logging

logger = logging.getLogger(__name__)
logger.info("MongoAdminSite chargé avec succès")    

urlpatterns = [
    path('mongo-test/', test_view), 
    path('mongo-admin/', mongo_admin_site.urls),  # Interface MongoDB Admin
    path('admin/', admin.site.urls),  # Interface admin standard
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('data_cleaning/', include('data_cleaning.urls', namespace='data_cleaning')),

]

CortexLab/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('projets/', views.projets_view, name='projets'),
    path('projets/create/', views.create_project, name='create_project'),
    path('projets/<str:id>/', views.view_project, name='view_project'),
    path('projets/<str:id>/analyze_data/', views.analyze_data, name='analyze_data'),
    path('projets/<str:id>/set_target/', views.set_target, name='set_target'),
    path('projets/<str:id>/set_features/', views.set_features, name='set_features'),
    path('projets/<str:id>/set_model_type/', views.set_model_type, name='set_model_type'),
    path('projets/<str:id>/delete_dataset/', views.delete_dataset, name='delete_dataset'),
    path('projets/<str:id>/prepare_analyze/', views.prepare_analyze, name='prepare_analyze'),
    path('projets/<str:id>/update_selected_datasets/', views.update_selected_datasets, name='update_selected_datasets'),

]

CortexLab/main/urls.py
from django.urls import path

from .views import base_view, dashboard_home

app_name = 'main'

urlpatterns = [
    path('', base_view, name='base'),
    path('dashboard/', dashboard_home, name='dashboard_home'),  # URL de tableau de bord
]

CortexLab/dashboard/models.py
from mongoengine import Document, EmbeddedDocument, StringField, ListField, EmbeddedDocumentField, DateTimeField
import uuid


class ColumnData(EmbeddedDocument):
    name = StringField(required=True)
    values = ListField()


class Dataset(EmbeddedDocument):
    id = StringField(default=lambda: str(uuid.uuid4()), unique=True)
    name = StringField(required=True)
    columns = ListField(EmbeddedDocumentField(ColumnData), default=list)
    uploaded_at = DateTimeField(required=True)


class Project(Document):
    user_id = StringField(required=True)
    name = StringField(max_length=255, required=True)
    model_type = StringField(max_length=50, choices=[
        ('clustering', 'Clustering'),
        ('regression', 'Régression'),
        ('classification', 'Classification'),
    ], required=False, null=True)
    datasets = ListField(EmbeddedDocumentField(Dataset), default=list)
    target = StringField(required=False, null=True)
    features = ListField(StringField(), default=list)
    created_at = DateTimeField()
    description = StringField(max_length=255, required=False)
    meta = {
        'collection': 'project',
        'db_alias': 'default',
    }

CortexLab/dashboard/forms.py
# dashboard/forms.py
from django import forms


class ProjectForm(forms.Form):
    name = forms.CharField(max_length=255, label='Nom du Projet', required=True)
    description = forms.CharField(
        max_length=255,
        label='Description',
        required=False,
        widget=forms.Textarea(attrs={'rows': 3, 'placeholder': 'Ajoutez une description du projet (facultatif)'})
    )

CortexLab/dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, Http404
from django.urls import reverse
from django.utils import timezone
from .models import Project, Dataset
from .forms import ProjectForm
from .utils import validate_and_prepare_dataset, delete_dataset_from_project
from bson import ObjectId
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages


@login_required
def projets_view(request):
    projects = Project.objects(user_id=str(request.user.id))
    return render(request, 'dashboard/projets.html', {'projects': projects})


@login_required
def create_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = Project(
                user_id=str(request.user.id),
                name=form.cleaned_data['name'],
                description=form.cleaned_data.get('description', ''),
                created_at=timezone.now()
            )
            project.save()
            return redirect('dashboard:view_project', id=str(project.id))
    else:
        form = ProjectForm()

    return render(request, 'dashboard/create_projet.html', {'form': form})


@login_required
def view_project(request, id):
    try:
        project = Project.objects.get(id=ObjectId(id), user_id=str(request.user.id))
    except Project.DoesNotExist:
        raise Http404("Projet non trouvé")

    return render(request, "dashboard/view_project.html", {"project": project})


@csrf_exempt
@login_required
def analyze_data(request, id):
    print("La fonction `analyze_data` est appelée.")  # Log
    if request.method == "POST" and 'file' in request.FILES:
        try:
            # Récupérer le projet
            project = Project.objects.get(id=ObjectId(id), user_id=str(request.user.id))
        except Project.DoesNotExist:
            messages.error(request, "Projet non trouvé.")
            return redirect(reverse('dashboard:view_project', args=[id]))
        
        file = request.FILES['file']
        dataset_name = request.POST.get('dataset_name', file.name)

        try:
            # Validation et préparation du dataset
            dataset_data = validate_and_prepare_dataset(file, dataset_name)
        except ValueError as e:
            messages.error(request, f"Erreur dans le dataset : {str(e)}")
            return redirect(reverse('dashboard:view_project', args=[id]))

        # Ajouter le dataset au projet
        try:
            new_dataset = Dataset(**dataset_data)
            project.datasets.append(new_dataset)
            project.save()
        except Exception as e:
            messages.error(request, f"Erreur lors de l'enregistrement du dataset : {str(e)}")
            return redirect(reverse('dashboard:view_project', args=[id]))

        # Réponse JSON en cas de succès
        messages.success(request, "Dataset ajouté avec succès.")
        # Rester sur la même page après succès
        return redirect(reverse('dashboard:view_project', args=[id]))

    messages.error(request, "Requête invalide.")
    return redirect(reverse('dashboard:view_project', args=[id]))



@csrf_exempt
@login_required
def delete_dataset(request, id):
    """
    Supprime un dataset spécifique du projet et recharge la page.
    """
    if request.method == "POST":
        dataset_id = request.POST.get("dataset_id")
        if not dataset_id:
            messages.error(request, "ID du dataset manquant")
            return redirect('dashboard:view_project', id=id)

        try:
            delete_dataset_from_project(id, dataset_id)
            messages.success(request, "Dataset supprimé avec succès.")
        except ValueError as e:
            messages.error(request, str(e))

        # Redirection vers la page du projet après suppression
        return redirect('dashboard:view_project', id=id)

    messages.error(request, "Méthode non autorisée.")
    return redirect('dashboard:view_project', id=id)


@login_required
def set_target(request, id):
    if request.method == "POST":
        try:
            project = Project.objects.get(id=ObjectId(id), user_id=str(request.user.id))
        except Project.DoesNotExist:
            return JsonResponse({"error": "Projet non trouvé."}, status=404)

        target_name = request.POST.get('target')
        if not target_name:
            return JsonResponse({"error": "Aucune cible sélectionnée."}, status=400)

        column_names = [col.name for col in project.datasets[0].columns]
        if target_name not in column_names:
            return JsonResponse({"error": f"Colonne cible invalide : {target_name}"}, status=400)

        project.target = target_name
        project.save()

        return JsonResponse({"message": "Cible enregistrée avec succès."})

    return JsonResponse({"error": "Méthode non autorisée."}, status=405)


@login_required
def set_features(request, id):
    if request.method == "POST":
        try:
            project = Project.objects.get(id=ObjectId(id), user_id=str(request.user.id))
        except Project.DoesNotExist:
            return JsonResponse({"error": "Projet non trouvé."}, status=404)

        selected_features = request.POST.getlist('features')
        if not selected_features:
            return JsonResponse({"error": "Aucune caractéristique sélectionnée."}, status=400)

        column_names = [col.name for col in project.datasets[0].columns]
        invalid_features = [f for f in selected_features if f not in column_names]
        if invalid_features:
            return JsonResponse({"error": f"Colonnes invalides : {invalid_features}"}, status=400)

        project.features = selected_features
        project.save()

        return JsonResponse({"message": "Caractéristiques enregistrées avec succès."})

    return JsonResponse({"error": "Méthode non autorisée."}, status=405)


@login_required
def set_model_type(request, id):
    if request.method == 'POST':
        try:
            project = Project.objects.get(id=ObjectId(id), user_id=str(request.user.id))
        except Project.DoesNotExist:
            return JsonResponse({"error": "Projet non trouvé."}, status=404)

        data = json.loads(request.body)
        model_type = data.get('model_type')

        if model_type not in ['clustering', 'regression', 'classification']:
            return JsonResponse({"error": "Type de modèle invalide"}, status=400)

        project.model_type = model_type
        project.save()

        return JsonResponse({"message": "Type de modèle enregistré avec succès."})

    return JsonResponse({"error": "Méthode non autorisée."}, status=405)


@login_required
def prepare_analyze(request, id):
    print('function : prepare_analyse')
    if request.method == "POST":
        data = json.loads(request.body)
        selected_datasets = data.get("selected_datasets", [])
        request.session["current_project_id"] = id
        request.session["selected_datasets"] = selected_datasets
        request.session.modified = True  # Important pour sauvegarder la session
        print(f"Session updated: project_id={id}, selected_datasets={selected_datasets}")
        return JsonResponse({"redirect_url": "/data_cleaning/analyze/"})
    return JsonResponse({"error": "Méthode non autorisée."}, status=405)

@csrf_exempt
@login_required
def update_selected_datasets(request, id):
    print('fucntion udupdate_selected_datasets')
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            print(data)
            selected_datasets = data.get("selected_datasets", [])
            print(selected_datasets)
            # Mettre à jour la session avec les datasets sélectionnés
            request.session["selected_datasets"] = selected_datasets
            request.session.modified = True  # Marquer la session comme modifiée
            return JsonResponse({"message": "Datasets sélectionnés mis à jour."})
        except Exception as e:
            return JsonResponse({"error": f"Erreur lors de la mise à jour : {str(e)}"}, status=400)
    return JsonResponse({"error": "Méthode non autorisée."}, status=405)

CortexLab/dashboard/templates/dashboard/create_projet.html
{% extends 'main/dashboard_home.html' %}

{% block content %}
  <h2>Créer un nouveau projet</h2>

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  {% if form.errors %}
    <div class="alert alert-danger">
      <p>Veuillez corriger les erreurs suivantes :</p>
      <ul>
        {% for field, errors in form.errors.items %}
          <li>{{ field }} : {{ errors|join:", " }}</li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  <form method="post" class="form">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_name">Nom du Projet :</label>
      {{ form.name }}
      <small class="text-danger">{{ form.name.errors }}</small>
    </div>
    <div class="form-group">
      <label for="id_description">Description (Facultatif) :</label>
      {{ form.description }}
      <small class="text-danger">{{ form.description.errors }}</small>
    </div>
    <button type="submit" class="btn btn-primary">Créer le projet</button>
  </form>
{% endblock %}

CortexLab/dashboard/templates/dashboard/projets.html
{% extends 'main/dashboard_home.html' %}

{% block content %}
  <h2>Vos Projets</h2>

  <p>
    <a href="{% url 'dashboard:create_project' %}" class="btn btn-success">Créer un nouveau projet</a>
  </p>

  <!-- Affichage de débogage -->
  <!--<p>Debug - Nombre de projets : {{ projects|length }}</p>-->

  {% if projects %}
    <ul>
      {% for project in projects %}
        <li>
          <a href="{% url 'dashboard:view_project' project.id %}">{{ project.name }}</a>
          - {{ project.get_model_type_display }}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Aucun projet enregistré pour le moment.</p>
  {% endif %}
{% endblock %}

CortexLab/dashboard/templates/dashboard/view_project.html
{% extends 'main/dashboard_home.html' %}
{% load static %}

{% block content %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">
{% endblock %}

<div class="container-fluid d-flex">
    <!-- Sidebar -->
    <div class="sidebar">
        <h3>Actions</h3>
        <!-- Bouton qui ouvre la modal -->
        <h3 class="mt-4">Importer vos datasets <i class="bi bi-file-earmark-arrow-up text-primary" style="font-size: 1.2rem;"></i></h3>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#uploadModal"><i class="bi bi-file-earmark-arrow-up me-2" style="font-size: 1.2rem;"></i>
            Télécharger des données 

        </button>

        <!--Fenêtre de la modal -->

        <div class="modal fade" id="uploadModal" tabindex="-1" aria-labelledby="uploadModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="uploadModalLabel">Télécharger des données</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="uploadForm" method="post" enctype="multipart/form-data" action="{% url 'dashboard:analyze_data' project.id %}">
                            <!-- Ajoutez ceci pour vérifier -->
                            <p>URL générée : {% url 'dashboard:analyze_data' project.id %}</p>
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="datasetName" class="form-label">Nom du Dataset</label>
                                <input type="text" class="form-control" id="datasetName" name="dataset_name" placeholder="Entrez un nom pour le dataset" required>
                            </div>
                            <div class="mb-3">
                                <label for="fileInput" class="form-label">Choisissez un fichier</label>
                                <input type="file" class="form-control" id="fileInput" name="file" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Envoyer</button>
                        </form>
                        
                        
                    </div>
                </div>
            </div>
        </div>

        <!-- Section pour Analyser les datasets -->
    <h3 class="mt-4">Analyser les datasets <i class="bi bi-eye text-primary" title="Sélectionner pour analyse"></i> </h3>
    <p class="text-white-50">Envoyez les datasets sélectionnés vers la page d'analyse.</p>
    <button id="analyze-btn" class="btn btn-primary w-100">
        <i class="bi bi-bar-chart-line"></i> Analyser
    </button>


        <h3>Type de modèle</h3>
        <form id="modelTypeForm">
            <select name="model_type" class="form-select mb-3" id="model_type">
                <option value="" disabled>-- Sélectionnez un type --</option>
                <option value="clustering">Clustering</option>  <i class="bi bi-trash" style="font-size: 1.2rem;"></i>
                <option value="regression">Régression</option>
                <option value="classification">Classification</option>
            </select>
            <button type="submit" class="btn btn-primary w-100">Enregistrer</button>
        </form>
    </div>

    <!-- Content -->  <i class="bi bi-trash" style="font-size: 1.2rem;"></i>
    <div class="content flex-grow-1" id="project-container" data-project-id="{{ project.id }}">
        <h2>Détails du Projet</h2>
        <p><strong>Nom :</strong> {{ project.name }}</p>
        <p><strong>Type de modèle :</strong> {{ project.get_model_type_display|default:"Non défini" }}</p>



<!-- Section des datasets -->
<h3>Datasets du Projet</h3>
<div class="row g-3" id="datasets-container">
    {% if project.datasets %}
        {% for dataset in project.datasets %}
        <div class="col-md-4 dataset-card-container" data-id="{{ dataset.id }}">
            <div class="card dataset-card shadow-sm h-100">
                <div class="card-header text-center">
                    <h5 class="card-title mb-0">{{ dataset.name }}</h5>
                </div>
                <div class="card-body text-center">
                    <img src="{% static 'dashboard/icons/dataset-icon.webp' %}" alt="Dataset Icon" class="img-fluid mb-2" style="max-height: 60px;">
                    <p class="mb-1"><small>Date : {{ dataset.uploaded_at }}</small></p>
                    <p class="mb-0"><small>Colonnes : {{ dataset.columns|length }}</small></p>
                </div>
                <div class="card-footer d-flex justify-content-between align-items-center bg-light">
                    <label class="form-check-label d-flex align-items-center mb-0">
                        <input 
                            type="checkbox" 
                            class="form-check-input dataset-checkbox me-2" 
                            data-id="{{ dataset.id }}"
                            title="Sélectionner pour analyse">
                        <i class="bi bi-eye text-primary" style="font-size: 1.2rem;"></i>
                    </label>
                    <button class="btn btn-link text-primary p-0" title="Analyser">
                        <i class="bi bi-bar-chart-line" style="font-size: 1.4rem;"></i>
                    </button>
                    <form class="delete-dataset-form mb-0" method="POST" action="{% url 'dashboard:delete_dataset' project.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="dataset_id" value="{{ dataset.id }}">
                        <button type="submit" class="btn btn-danger btn-sm" title="Supprimer">
                            <i class="bi bi-trash" style="font-size: 1.2rem;"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <p class="text-muted">Aucun dataset disponible.</p>
    {% endif %}
</div>




        <!-- Résumé des actions -->
        <h3>Résumé</h3>
        <p><strong>Features :</strong> {{ project.features|default:"Aucune" }}</p>
        <p><strong>Target :</strong> {{ project.target|default:"Non définie" }}</p>
    </div>
</div>

<script src="{% static 'dashboard/js/dashboard.js' %}"></script>
{% endblock %}